### ISSUE TITLE
Supplementing a custom animation for the default animation

### ISSUE THREAD

**Issue by KMaragh** [iPaulPro/Android-ItemTouchHelper-Demo#1]
I noticed your medium post and I think it was a great tutorial on how to use the Android supported ItemTouchHelper for a recyclerview. I'm not sure if you have this planned in the future, but if you can demonstrate how to replace the default swipe animation that comes with an ItemTouchHelper with your own custom view animation, I feel this tutorial will be even more complete.

**Comment by iPaulPro** [comment]
Thanks, @KMaragh. Part two will cover custom swipe animations and show how to control the item views during moves and swipes. You can see a peak of this in `onChildDraw` in the Master branch  [SimpleItemTouchHelperCallback](https://github.com/iPaulPro/Android-ItemTouchHelper-Demo/blob/master/app%2Fsrc%2Fmain%2Fjava%2Fco%2Fpaulburke%2Fandroid%2Fitemtouchhelperdemo%2Fhelper%2FSimpleItemTouchHelperCallback.java). It shows how to fade the view out as it is swiped.

Note that since ItemTouchHelper is really just a `RecyclerView.ItemDecoration`, you can use `onChildDraw` and `onChildDrawOver` as you would normally. However, now you have the distance of the movement provided as a parameter, as well as the state (drag or swipe).

**Comment by pixelbendr** [comment]
Please when are you releasing part 2?

**Comment by iPaulPro** [comment]
Part 2 is released: https://medium.com/@ipaulpro/drag-and-swipe-with-recyclerview-6a6f0c422efd

It shows a very basic control over swipe animations. I had to split the example into two parts, so Part 3 will dive even further into this (including leave-behinds and drag animation control).

**Comment by pixelbendr** [comment]
Thanks for this Paul. You are AWESOME!

**Comment by diegotrrs** [comment]
Hello Paul! Your first two tutorial were extremely useful! Are you planning on releasing the third part? I need to implement custom swipe animations. I need to display two different views (one when the user swipes to the right and a different one when the user swipes to the left) I'm attaching an example.

Anyway, Thank you :)
<img width="298" alt="screen shot 2016-03-11 at 10 57 59 pm" src="https://cloud.githubusercontent.com/assets/7862525/13720940/bc26e5cc-e7dc-11e5-9eac-306ee46aacf9.png">

**Comment by KMaragh** [comment]
Didn't realize I still had this open :). Going to close it.
